In [1]:
import torch

In [2]:
t = torch.arange(0, 5).type(torch.LongTensor)

In [3]:
t

tensor([0, 1, 2, 3, 4])

In [24]:
y = x = torch.tensor([1, 2, 3, 4, 5]) 

In [25]:
t2 = t * y

In [26]:
t2

tensor([ 0,  2,  6, 12, 20])

In [6]:
t3 = t2.unsqueeze(1)

In [7]:
t3

tensor([[ 0],
        [ 5],
        [10],
        [15],
        [20]])

In [8]:
t4 = t2.unsqueeze(0)

In [9]:
t4

tensor([[ 0,  5, 10, 15, 20]])

In [10]:
t5 = t2.unsqueeze(2)

RuntimeError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [11]:
t5

NameError: name 't5' is not defined

In [12]:
x = torch.tensor([1, 2, 3, 4]) 

In [13]:
x.shape

torch.Size([4])

In [14]:
x1 = torch.unsqueeze(x, 0) 

In [15]:
x1

tensor([[1, 2, 3, 4]])

In [16]:
x1.shape

torch.Size([1, 4])

In [18]:
x2 = torch.unsqueeze(x, 1) 

In [19]:
x2

tensor([[1],
        [2],
        [3],
        [4]])

In [20]:
x2.shape

torch.Size([4, 1])